### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by the94air** [bradlc/vscode-tailwindcss#23]
- Issue Type: `Performance`
- Extension Name: `vscode-tailwindcss`
- Extension Version: `0.1.16`
- OS Version: `Linux x64 4.15.0-43-generic`
- VSCode version: `1.30.1`

[bradlc.vscode-tailwindcss-unresponsive.cpuprofile.txt](https://github.com/bradlc/vscode-tailwindcss/files/2735415/bradlc.vscode-tailwindcss-unresponsive.cpuprofile.txt)

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

**Comment by bradlc** [comment]
Hey @the94air. Thanks for this. It looks like a lot of time is spent in tasks relating to PostCSS. Perhaps due to a large Tailwind config?

I am currently working on a large restructure of the extension which will use the Language Server Protocol. This should improve performance and prevent the extension from affecting the performance of other extensions.

I’ll leave this issue open and let you know when the new version is released; hopefully it will be better!

**Comment by mjhorninger** [comment]
@bradlc I also had this come up, and closed #26 (auto created), as it seemed like a dup of it.

**Comment by bradlc** [comment]
The extension has just received a big update and now uses a langauge server, which should improve performance a lot. Please open a new issue if you still have problems, thanks!

**Comment by the94air** [comment]
Great upgrade. Thanks man!
