### ISSUE TITLE
Intellisense works, but shows CSS errors

### ISSUE THREAD

**Issue by mweiczorek** [bradlc/vscode-tailwindcss#78]
Hi,

The extension works as far as intellisense suggestions are concerned, but the actual CSS file is showing warnings with the `@tailwind` directive and errors on the class names after the `@apply` directive (but not on the `@apply` itself).

I've disabled all other CSS-related extensions and linters to no avail.
Using the latest version of the extension (0.2.0)
Using the latest version of code

![notworking](https://user-images.githubusercontent.com/224439/66453796-f35eea80-eaa8-11e9-939a-908b9da7ad31.png)

![notworking2](https://user-images.githubusercontent.com/224439/66453870-35882c00-eaa9-11e9-8bb4-c340aa0fae41.png)

![notworking3](https://user-images.githubusercontent.com/224439/66453899-53559100-eaa9-11e9-853e-aeb76e68e0a5.png)

**Comment by hacknug** [comment]
This is not an issue with the extension. Disable CSS validation if you don't want VSCode to complain about you using an invalid syntax for CSS: `"css.validate": false`

**Comment by mweiczorek** [comment]
That hardly seems like a solution. Plenty of other extensions can coexist with formatters and linters when they introduce custom syntax or tags. The object is not to abandon all syntax-checking - it's like killing a fly with a shotgun. If it's all the same, I'd rather hear from someone involved in the project.

**Comment by hacknug** [comment]
> Plenty of other extensions can coexist with formatters and linters when they introduce custom syntax or tags.

The thing is you're complaining about syntax issues in the repo of an extension that doesn't do anything related to syntaxes. It _only_ gives you suggestions for classes generated by your Tailwind config file.

You either start using Stylelint and configure it so it doesn't complain about these things or you'll see them.

**Comment by gDelgado14** [comment]
I'm having the same issue, and there isn't any documentation in this repo to explain how to attain the same behaviour as illustrated in the extension's [README](https://github.com/bradlc/vscode-tailwindcss/blob/master/README.md). Here is what I'm seeing:

<img width="476" alt="Screen Shot 2019-11-10 at 3 07 45 PM" src="https://user-images.githubusercontent.com/10621548/68549932-e137db00-03cb-11ea-9a72-0299e7740ff0.png">

**Comment by ycs77** [comment]
Install this vscode extension: [stylelint](https://marketplace.visualstudio.com/items?itemName=thibaudcolas.stylelint). And add this setting:

```json
{
  "css.validate": false,
  "stylelint.config": {
    "rules": {
      "at-rule-no-unknown": [true, {
        "ignoreAtRules": [
          "tailwind",
          "apply",
          "variants",
          "responsive",
          "screen"
        ]
      }],
      "declaration-block-trailing-semicolon": null,
      "no-descending-specificity": null
    }
  }
}
```

**Comment by bradlc** [comment]
I'm going to close this because as @hacknug said this is not an issue with the extension. Unfortunately (as far as I'm aware) extensions cannot hook into the built-in CSS validation that VS Code does (without registering an entirely new language mode). The suggestions from @hacknug  and @ycs77 are both good options 👍 Alternatively you can install [a postcss extension](https://marketplace.visualstudio.com/items?itemName=ricard.PostCSS) and set that as the default for CSS files:

```
"files.associations": {
  "*.css": "postcss"
}
```

**Comment by bbugh** [comment]
The stylelint link above is out of date, the extension was renamed to stylelint.vscode-stylelint in the [v0.60.0 release](https://github.com/stylelint/vscode-stylelint/releases/tag/v0.60.0).

The new link is https://marketplace.visualstudio.com/items?itemName=stylelint.vscode-stylelint

**Comment by dmzza** [comment]
I believe the right way to get rid of VS Code's CSS errors is to install language support for PostCSS, as suggested above. [PostCSS Language Support](https://marketplace.visualstudio.com/items?itemName=csstools.postcss) looks like the best extension out there right now, and merely installing it will make it the default language for `.css` files. That's fine for projects that don't use PostCSS too, because:
> **PostCSS Language Support** is derived from the native **CSS Language Support** built into **Visual Studio Code**

All you have to do is [install it](https://marketplace.visualstudio.com/items?itemName=csstools.postcss). No further configuration necessary.

**Comment by pranav-js** [comment]
this doesn't work for SCSS files unfortuantely

**Comment by Bishwas-py** [comment]
Giving 
```
Semicolon or block is expected svelte(css-syntax-error)

```

**Comment by jldec** [comment]
Since #518 this extension can be configured to act as replacement for VS Code CSS IntelliSense.
See [marketplace](https://marketplace.visualstudio.com/items?itemName=bradlc.vscode-tailwindcss#recommended-vs-code-settings) or [README](https://github.com/tailwindlabs/tailwindcss-intellisense#recommended-vs-code-settings).

> Use the `files.associations` setting to tell VS Code to always open `.css` files in Tailwind CSS mode:
>
> ```
> "files.associations": {
>   "*.css": "tailwindcss"
> }
> ```

<img width="695" alt="Screenshot 2023-02-06 at 11 47 32 AM" src="https://user-images.githubusercontent.com/849592/216963864-d7140a60-e7cd-411e-bd38-b9c6b16297d0.png">
